### ISSUE TITLE
导入抽卡记录报错 UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by A7424** [monsterxcn/nonebot-plugin-gachalogs#10]
![Uploading FQIYFM6N6X2R5PD1]OXUUO0.png…]()

**Comment by monsterxcn** [comment]
？

**Comment by A7424** [comment]
> ？
不知道为什么图片发不过去

**Comment by A7424** [comment]
```
[04-08 01:02:22 [ERROR] nonebot | Running Matcher(type='notice', module=nonebot_plugin_gachalogs) failed.
Traceback (most recent call last):
  File "bot.py", line 17, in <module>
    nonebot.run()
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\QC\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_gachalogs\__init__.py", line 312, in gotFile
    importRes = await importGachaFile(sender, fileData, bot.config.superusers)
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_gachalogs\data_import.py", line 354, in importGachaFile
    data = await getFileData(file["url"])
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\nonebot_plugin_gachalogs\data_import.py", line 125, in getFileData
    return res.json()
  File "D:\jqr\nonebot2\nb2\.venv\lib\site-packages\httpx\_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 321: invalid start byte](url)

**Comment by A7424** [comment]
![FQIYFM6N6X2R5PD1 OXUUO0](https://user-images.githubusercontent.com/103619507/230648619-66e418b5-2ff4-4494-bf42-63d6dd436dec.png)

**Comment by monsterxcn** [comment]
文件编码格式不对，允许的导入文件必须为 UTF-8 编码格式。
